apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-client
  labels:
    app: front-end
spec:
  replicas: 2
  selector:
   matchLabels:
    app: front-end
  template:
    metadata:
      name: shopping-client
      labels:
          app: front-end
    spec:
      containers:
        - name: shopping-client-container
          image: giantmath/shoppingclient:latest
          ports:
            - containerPort: 5001
          imagePullPolicy: Always
          readinessProbe:
            tcpSocket: 
              port: 5001
            initialDelaySeconds: 1
            periodSeconds: 10
              
---
apiVersion: v1
kind: Service
metadata:
  name: shoppingclient-service
spec:
  type: NodePort
  selector:
    app: front-end
  ports:
    - port: 5001
      targetPort: 5001
      nodePort: 30005